# Generated by Django 4.1.9 on 2023-05-28 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojo', '0181_vulnerability_id_exploit_prediction_percentile_and_more'),
        ('dojo', '0185_product_disable_sla_breach_notifications_and_more'),
    ]

    operations = [
    ]
